package com.kyh.system.mapper;

import com.kyh.system.model.Setting;
import com.kyh.system.model.SettingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tg_setting
     *
     * @mbg.generated
     */
    long countByExample(SettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tg_setting
     *
     * @mbg.generated
     */
    int deleteByExample(SettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tg_setting
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("category1") Integer category1, @Param("category2") Integer category2, @Param("category3") Integer category3);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tg_setting
     *
     * @mbg.generated
     */
    int insert(Setting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tg_setting
     *
     * @mbg.generated
     */
    int insertSelective(Setting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tg_setting
     *
     * @mbg.generated
     */
    List<Setting> selectByExample(SettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tg_setting
     *
     * @mbg.generated
     */
    Setting selectByPrimaryKey(@Param("category1") Integer category1, @Param("category2") Integer category2, @Param("category3") Integer category3);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tg_setting
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Setting record, @Param("example") SettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tg_setting
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Setting record, @Param("example") SettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tg_setting
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Setting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tg_setting
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Setting record);
}