package com.kyh.system.mapper;

import com.kyh.system.model.Syain;
import com.kyh.system.model.SyainExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SyainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syain_main
     *
     * @mbg.generated
     */
    long countByExample(SyainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syain_main
     *
     * @mbg.generated
     */
    int deleteByExample(SyainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syain_main
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer syainId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syain_main
     *
     * @mbg.generated
     */
    int insert(Syain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syain_main
     *
     * @mbg.generated
     */
    int insertSelective(Syain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syain_main
     *
     * @mbg.generated
     */
    List<Syain> selectByExample(SyainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syain_main
     *
     * @mbg.generated
     */
    Syain selectByPrimaryKey(Integer syainId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syain_main
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Syain record, @Param("example") SyainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syain_main
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Syain record, @Param("example") SyainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syain_main
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Syain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syain_main
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Syain record);
}