package com.kyh.system.mapper;

import com.kyh.system.model.UserAccessLog;
import com.kyh.system.model.UserAccessLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserAccessLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_access_log
     *
     * @mbg.generated
     */
    long countByExample(UserAccessLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_access_log
     *
     * @mbg.generated
     */
    int deleteByExample(UserAccessLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_access_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_access_log
     *
     * @mbg.generated
     */
    int insert(UserAccessLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_access_log
     *
     * @mbg.generated
     */
    int insertSelective(UserAccessLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_access_log
     *
     * @mbg.generated
     */
    List<UserAccessLog> selectByExample(UserAccessLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_access_log
     *
     * @mbg.generated
     */
    UserAccessLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_access_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserAccessLog record, @Param("example") UserAccessLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_access_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserAccessLog record, @Param("example") UserAccessLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_access_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserAccessLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_access_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserAccessLog record);
}