package com.kyh.system.model;

public class Setting {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tg_setting.category1
     *
     * @mbg.generated
     */
    private Integer category1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tg_setting.category2
     *
     * @mbg.generated
     */
    private Integer category2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tg_setting.category3
     *
     * @mbg.generated
     */
    private Integer category3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tg_setting.value1
     *
     * @mbg.generated
     */
    private String value1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tg_setting.value2
     *
     * @mbg.generated
     */
    private String value2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tg_setting.value3
     *
     * @mbg.generated
     */
    private String value3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tg_setting.display_order
     *
     * @mbg.generated
     */
    private Integer displayOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tg_setting.delete_flag
     *
     * @mbg.generated
     */
    private Integer deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tg_setting.category1
     *
     * @return the value of tg_setting.category1
     *
     * @mbg.generated
     */
    public Integer getCategory1() {
        return category1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tg_setting.category1
     *
     * @param category1 the value for tg_setting.category1
     *
     * @mbg.generated
     */
    public void setCategory1(Integer category1) {
        this.category1 = category1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tg_setting.category2
     *
     * @return the value of tg_setting.category2
     *
     * @mbg.generated
     */
    public Integer getCategory2() {
        return category2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tg_setting.category2
     *
     * @param category2 the value for tg_setting.category2
     *
     * @mbg.generated
     */
    public void setCategory2(Integer category2) {
        this.category2 = category2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tg_setting.category3
     *
     * @return the value of tg_setting.category3
     *
     * @mbg.generated
     */
    public Integer getCategory3() {
        return category3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tg_setting.category3
     *
     * @param category3 the value for tg_setting.category3
     *
     * @mbg.generated
     */
    public void setCategory3(Integer category3) {
        this.category3 = category3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tg_setting.value1
     *
     * @return the value of tg_setting.value1
     *
     * @mbg.generated
     */
    public String getValue1() {
        return value1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tg_setting.value1
     *
     * @param value1 the value for tg_setting.value1
     *
     * @mbg.generated
     */
    public void setValue1(String value1) {
        this.value1 = value1 == null ? null : value1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tg_setting.value2
     *
     * @return the value of tg_setting.value2
     *
     * @mbg.generated
     */
    public String getValue2() {
        return value2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tg_setting.value2
     *
     * @param value2 the value for tg_setting.value2
     *
     * @mbg.generated
     */
    public void setValue2(String value2) {
        this.value2 = value2 == null ? null : value2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tg_setting.value3
     *
     * @return the value of tg_setting.value3
     *
     * @mbg.generated
     */
    public String getValue3() {
        return value3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tg_setting.value3
     *
     * @param value3 the value for tg_setting.value3
     *
     * @mbg.generated
     */
    public void setValue3(String value3) {
        this.value3 = value3 == null ? null : value3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tg_setting.display_order
     *
     * @return the value of tg_setting.display_order
     *
     * @mbg.generated
     */
    public Integer getDisplayOrder() {
        return displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tg_setting.display_order
     *
     * @param displayOrder the value for tg_setting.display_order
     *
     * @mbg.generated
     */
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tg_setting.delete_flag
     *
     * @return the value of tg_setting.delete_flag
     *
     * @mbg.generated
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tg_setting.delete_flag
     *
     * @param deleteFlag the value for tg_setting.delete_flag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}