package com.kyh.system.model;

public class UserAuth {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.user_code
     *
     * @mbg.generated
     */
    private String userCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.user_role
     *
     * @mbg.generated
     */
    private String userRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.is_youkou
     *
     * @mbg.generated
     */
    private Integer isYoukou;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.user_id
     *
     * @return the value of user_auth.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.user_id
     *
     * @param userId the value for user_auth.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.user_code
     *
     * @return the value of user_auth.user_code
     *
     * @mbg.generated
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.user_code
     *
     * @param userCode the value for user_auth.user_code
     *
     * @mbg.generated
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.user_name
     *
     * @return the value of user_auth.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.user_name
     *
     * @param userName the value for user_auth.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.password
     *
     * @return the value of user_auth.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.password
     *
     * @param password the value for user_auth.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.user_role
     *
     * @return the value of user_auth.user_role
     *
     * @mbg.generated
     */
    public String getUserRole() {
        return userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.user_role
     *
     * @param userRole the value for user_auth.user_role
     *
     * @mbg.generated
     */
    public void setUserRole(String userRole) {
        this.userRole = userRole == null ? null : userRole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.is_youkou
     *
     * @return the value of user_auth.is_youkou
     *
     * @mbg.generated
     */
    public Integer getIsYoukou() {
        return isYoukou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.is_youkou
     *
     * @param isYoukou the value for user_auth.is_youkou
     *
     * @mbg.generated
     */
    public void setIsYoukou(Integer isYoukou) {
        this.isYoukou = isYoukou;
    }
}