package com.kyh.system.model;

import java.util.Date;

public class UserAccessLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_access_log.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_access_log.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_access_log.gamen_id
     *
     * @mbg.generated
     */
    private String gamenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_access_log.start_time
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_access_log.id
     *
     * @return the value of user_access_log.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_access_log.id
     *
     * @param id the value for user_access_log.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_access_log.user_id
     *
     * @return the value of user_access_log.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_access_log.user_id
     *
     * @param userId the value for user_access_log.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_access_log.gamen_id
     *
     * @return the value of user_access_log.gamen_id
     *
     * @mbg.generated
     */
    public String getGamenId() {
        return gamenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_access_log.gamen_id
     *
     * @param gamenId the value for user_access_log.gamen_id
     *
     * @mbg.generated
     */
    public void setGamenId(String gamenId) {
        this.gamenId = gamenId == null ? null : gamenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_access_log.start_time
     *
     * @return the value of user_access_log.start_time
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_access_log.start_time
     *
     * @param startTime the value for user_access_log.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
}