DROP TABLE IF EXISTS USER_ACCESS_LOG;

CREATE TABLE USER_ACCESS_LOG (
    ID SERIAL PRIMARY KEY,
    USER_ID INTEGER NOT NULL,
    GAMEN_ID VARCHAR(255),
    START_TIME TIMESTAMP
);

SELECT * 
FROM USER_ACCESS_LOG;

SELECT * FROM syain_main;
